# Generated by Django 4.2.7 on 2025-12-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_uploads/')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_transfers', models.IntegerField(default=0)),
                ('transfers_completed', models.IntegerField(default=0)),
            ],
        ),
    ]
