# Generated by Django 4.2.7 on 2025-12-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_transfers', '0001_initial'),
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransferjob',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfert.account'),
        ),
    ]
