# Generated by Django 4.2.7 on 2025-12-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulk_transfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_msisdn', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated in Django'), ('MOJALOOP_COMPLETED', 'Transfer Completed on Hub'), ('FAILED', 'Transfer Failed')], default='INITIATED', max_length=50)),
                ('transfer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('home_transaction_id', models.CharField(blank=True, max_length=64, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('sdk_response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='Transfert P2P', max_length=255)),
                ('bulk_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulk_transfers.bulktransferjob')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='transfert.account')),
            ],
        ),
    ]
